/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atm;

import java.util.concurrent.Callable;

import atm.Factories.user.UserGetFactory;
import infra.user.get.output.UserGetOutputData;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "app")
public class App implements Callable<Integer> {
	@Option(names = {"-u", "--user"}, description = "User name", interactive = true)
	char[] userName;
	
	@Option(names = {"-p", "--password"}, description = "User password", interactive = true)
	char[] userPassword;
	
    public static void main(String... args) {
        int exitCode = new CommandLine(new App()).execute("-u", "-p");
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception {
        String userNameString = new String(userName);
        String userPasswordString = new String(userPassword);
        
        UserGetFactory userGetFactory = new UserGetFactory();
        userGetFactory.getUserGetController().userGetInputData(userNameString, userPasswordString);
        UserGetOutputData userGetOutputData = userGetFactory.getUserGetPresenter().getUserGetOutputData();
        
        System.out.printf("USER ID: %d \n", userGetOutputData.getUserId());
        System.out.printf("USER BALANCE: %s \n", userGetOutputData.getUserBalance());
        System.out.printf("USER NAME: %s", userGetOutputData.getUserName());
        return 1;
    }
}
